export const LOAD_MAILS_REQUEST = 'LOAD_MAILS_REQUEST';
export const LOAD_MAILS_SUCCESS = 'LOAD_MAILS_SUCCESS';
export const LOAD_MAILS_FAILED = 'LOAD_MAILS_FAILED';

export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILED = 'SEND_MAIL_FAILED';
